dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.4

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update
  - sudo apt-get -y install git zip cli curl
#  - sudo apt-get -y install git zip php7.0-cli php7.0-curl
  - sudo pip install codecov

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

after_success:
  - codecov
